"""User

Revision ID: 1a9985dbb53a
Revises: 8eb1a5e440fc
Create Date: 2024-04-23 10:43:46.010913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a9985dbb53a'
down_revision: Union[str, None] = '8eb1a5e440fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('contacts_user_i_fkey', 'contacts', type_='foreignkey')
    op.create_foreign_key(None, 'contacts', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('contacts', 'user_i')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('user_i', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.create_foreign_key('contacts_user_i_fkey', 'contacts', 'users', ['user_i'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('contacts', 'user_id')
    # ### end Alembic commands ###
