"""User

Revision ID: 8eb1a5e440fc
Revises: b1047e7e2a79
Create Date: 2024-04-23 09:45:25.484972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eb1a5e440fc'
down_revision: Union[str, None] = 'b1047e7e2a79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('user_i', sa.Integer(), nullable=False))
    op.drop_constraint('contacts_user_fkey', 'contacts', type_='foreignkey')
    op.create_foreign_key(None, 'contacts', 'users', ['user_i'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('contacts', 'user')
    op.add_column('users', sa.Column('avatar', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    op.add_column('contacts', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.create_foreign_key('contacts_user_fkey', 'contacts', 'users', ['user'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('contacts', 'user_i')
    # ### end Alembic commands ###
