"""User

Revision ID: b1047e7e2a79
Revises: fe33f18f548e
Create Date: 2024-04-22 15:05:32.542533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1047e7e2a79'
down_revision: Union[str, None] = 'fe33f18f548e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'users', ['refresh_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'refresh_token')
    # ### end Alembic commands ###
